-- =========================================================================
-- TASKKER.IO - DISPLAY NAME SYNCHRONIZATION
-- This migration ensures `profiles.name` and `team_members.name` are 
-- tightly coupled via two-way triggers and automated user-creation pipelines.
-- =========================================================================

-- 1. Backfill existing profiles with the name from team_members where they match by user_id OR email
UPDATE public.profiles p
SET name = tm.name
FROM public.team_members tm
WHERE (p.id = tm.user_id OR p.email = tm.email)
  AND p.name IS NULL;

-- 2. Update the Auth trigger so future signups automatically pull their display name 
--    dynamically from the team_member record previously generated by the Admin
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER 
LANGUAGE plpgsql 
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_name TEXT;
BEGIN
  -- Try to find their pre-assigned name from team_members (via email link)
  SELECT name INTO v_name FROM public.team_members WHERE email = new.email LIMIT 1;
  
  -- Insert the new profile
  INSERT INTO public.profiles (id, email, role, name)
  VALUES (new.id, new.email, 'worker'::public.app_role, v_name);
  
  -- Link the team_member record to this real auth user so future edits stay linked
  UPDATE public.team_members 
  SET user_id = new.id 
  WHERE email = new.email;

  RETURN new;
END;
$$;

-- 3. Create Bidirectional Sync Triggers to ensure App.jsx renaming works reliably 
-- across both the Admin Team_Member map and the native Profile configuration.

-- Sync Trigger: If team_members.name is updated -> profile.name is synchronized
CREATE OR REPLACE FUNCTION public.sync_team_member_to_profile()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Utilizing IS DISTINCT FROM to prevent trigger recursion loops
  IF NEW.name IS DISTINCT FROM OLD.name THEN
    IF NEW.user_id IS NOT NULL THEN
      UPDATE public.profiles SET name = NEW.name WHERE id = NEW.user_id;
    ELSIF NEW.email IS NOT NULL THEN
      UPDATE public.profiles SET name = NEW.name WHERE email = NEW.email;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_team_member_name_change ON public.team_members;
CREATE TRIGGER on_team_member_name_change
  AFTER UPDATE OF name ON public.team_members
  FOR EACH ROW EXECUTE PROCEDURE public.sync_team_member_to_profile();

-- Sync Trigger: If profiles.name is updated -> team_members.name is synchronized
CREATE OR REPLACE FUNCTION public.sync_profile_to_team_member()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Utilizing IS DISTINCT FROM to prevent trigger recursion loops
  IF NEW.name IS NOT NULL AND NEW.name IS DISTINCT FROM OLD.name THEN
    UPDATE public.team_members SET name = NEW.name WHERE user_id = NEW.id OR email = NEW.email;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_profile_name_change ON public.profiles;
CREATE TRIGGER on_profile_name_change
  AFTER UPDATE OF name ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.sync_profile_to_team_member();
